spring:
  application:
    name: ms-local

  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 10000

  datasource:
    url: jdbc:mysql://78.47.233.52:3306/medsoft_demo
    username: app_java_user
    password: GOr0dJU1x86KAV3T!-283@1
    hikari:
      maximum-pool-size: 5

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: false

mode-config:
  time-slots:
    - requested-time: 3
      started-time: "08:00"
      end-time: "12:30"
      timeEnum: "ACTIVE"

    - requested-time: 15
      started-time: "12:30"
      end-time: "13:00"
      timeEnum: "PASSIVE"

    - requested-time: null
      started-time: "13:00"
      end-time: "13:30"
      timeEnum: "SLEEP"